<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-11-13T13:45:10+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Paris',
];
