<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-11-13T15:00:44+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'fr_FR',
    'version_installed' => '8.4.3',
    'version_db_installed' => '20180716000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1542117612,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
];
