<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-11-13T13:47:05+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'fr_FR',
    'version_installed' => '8.4.3',
    'version_db_installed' => '20180716000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1542113109,
        'latest_version' => '8.4.3',
    ],
];
