<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-11-13T13:45:10+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_url
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'LoSc5',
            'seo' => [
                'canonical_url' => 'http://losc5/',
            ],
        ],
    ],
];
